CREATE TABLE "CUSTOMER_INFO" (
  "CUSTOMER_SSN" NUMBER(10) NOT NULL PRIMARY KEY,
  "FIRST_NAME" VARCHAR2(100) NOT NULL,
  "LAST_NAME" VARCHAR2(100) NOT NULL UNIQUE,
  "BIRTH_DATE" NUMBER(2) NOT NULL,
  "BIRHT_MONTH" NUMBER(2) NOT NULL,
  "BIRTH_YEAR" NUMBER(4) NOT NULL,
  "PHONE_TYPE" VARCHAR2(100) NULL,
  "PHONE_NUMBER" NUMBER(10) NOT NULL UNIQUE,
  "CITY" VARCHAR2(100) NOT NULL,
  "STATE" VARCHAR2(100) NOT NULL,
  "STREET" VARCHAR2(100) NOT NULL,
  "ZIP" NUMBER(10) NOT NULL,
  "W2" CHAR(1) NOT NULL CHECK (BOOL IN ('N', 'Y'), 
  "TAX_RETURN" CHAR(1) NOT NULL CHECK (BOOL IN ('N', 'Y'),
  "CREDIT_REPORT" CHAR(1) NOT NULL CHECK (BOOL IN ('N', 'Y'),
  "BANK_INFO" VARCHAR2(100) NOT NULL,
  "PRIMARY_INCOME" DECIMAL(12,4) NULL,
  "SECONDARY_INCOME" DECIMAL(12,4) NULL,
   CREATE INDEX CUSTOMERINFO
   ON CUSTOMER_INFO (FIRST_NAME, LAST_NAME, BIRTH_DATE, BIRTH_MONTH, BIRTH_YEAR, PHONE_NUMBER)
   [COMPUTE STATISTICS] 
   CREATE INDEX CUSTOMERADDRESS 
   ON CUSTOMER_INFO (CITY, STATE, STREET, ZIP, BANK_INFO, PRIMARY_INCOME, SECONDARY_INCOME)
   [COMPUTE STATISTICS]
);

CREATE TABLE "MONTHLY_STATEMENT" (
  "STATEMENT_ID" NUMBER(10) NOT NULL PRIMARY KEY,
  "PRINCIPLE_BALANCE" DECIMAL(12,4) NOT NULL,
  "STATEMENT_DATE" TIMESTAMP NOT NULL,
  "PAYMENT_DUE_DATE" TIMESTAMP NOT NULL,
  "REMAINIG_PAYMENTS" DECIMAL(12,4) NOT NULL,
  "DATE_LAST_PAYMENT" TIMESTAMP NOT NULL,
   CREATE INDEX STATEMENT_MONTHLY
   ON CUSTOMER_INFO (PRINCIPLE_BALANCE, PAYMENT_DUE_DATE, REMAINING_PAYMENT)
   [COMPUTE STATISTICS]
);

CREATE TABLE "EMPLOYEES" (
  "EMPLOYEEID" NUMBER(10) NOT NULL PRIMARY KEY,
  "OFFICERID" NUMBER(10) NOT NULL UNIQUE,
  "IDENTIFIERID" NUMBER(10) NOT NULL UNIQUE,
  "EMPL_FIRST_NAME" VARCHAR2(100) NOT NULL,
  "EMPL_LAST_NAME" VARCHAR2(100) NOT NULL,
CONSTRAINT EMOLOYEES_OFFICER_FK 
FOREIGN KEY (OFFICERID)
REFERENCES EMPLOYEES (EMPLOYEEID)
CONSTRAINT EMLOYEE_INDENTIFIER_FK 
FOREIGN KEY (IDENTIFIERID)
REFERENCES EMLOYEES (EMLOYEEID)
ON UPDATE CASCADE
CREATE UNIQUE INDEX EMLOYEESINFO
   ON EMPLOYEES (EMPL_LAST_NAME)
  [COMPUTE STATISTICS]
);


CREATE TABLE "LOAN_APPLICATION_FORM" (
  "LOAN_ID" NUMBER(10) NOT NULL PRIMARY KEY,
  "INTEREST_RATE" NUMBER(10) NOT NULL,
  "LOAN_TYPE" VARCHAR2(100) NOT NULL,
  "MONTHLY_PAYMENT" DECIMAL(12,4) NOT NULL,
  "RESTRICTION_ON_LOAN" VARCHAR2(100) NOT NULL,
  "APLLICATION_DATE" TIMESTAMP NOT NULL,
  "LOAN_AMOUNT" DECIMAL(12,4) NOT NULL,
  "LOAN_TERM" VARCHAR2(100) NOT NULL,
  "CUSTOMER_SSN" NUMBER(10) NOT NULL,
  "EMPLOYEEID" NUMBER(10) NOT NULL,
  "STATEMENT_ID" NUMBER(10) NOT NULL,
CONSTRAINT CUSTOMER_FORM_FK 
FOREIGN KEY (CUSTOMER_SSN)
REFERENCES CUSTOMER_INFO (CUSTOMER_SSN)
CONSTRAINT EMLOYEE_FORM_FK 
FOREIGN KEY (EMLOYEEID)
REFERENCES EMLOYEES (EMLOYEEID)
CONSTRAINT FORM_STATEMENT_FK 
FOREIGN KEY (STATEMENT_ID)
REFERENCES MONTHLY_STATEMENT (STATEMENT_ID)
ON UPDATE CASCADE
CREATE INDEX APPLICATIONFORM 
   ON LOAN_APPLICATION_FORM (INTEREST_RATE, LOAN_TYPE, MONTHLY_PAYMENT, RESTRICTION_ON_LOAN, APPLICATION_DATE, LOAN_AMOUNT, LOAN_TERM)
  [COMPUTE STATISTICS]
);


CREATE TABLE "LOAN_PROCEED_DISBERSEMENT" (
  "CHECK_ID" NUMBER(10) NOT NULL PRIMARY KEY,
  "DISBERSEMENT_DATE" TIMESTAMP NOT NULL,
  "CHECK_AMOUNT" DECIMAL(12,4) NOT NULL,
  "LOAN_ID" NUMBER(10) NOT NULL,
  "STATEMENT_ID" NUMBER(10) NOT NULL,
CONSTRAINT DISBERSEMENT_LOAN_FK 
FOREIGN KEY (LOAN_ID)
REFERENCES LOAN_APPLICATION_FORM (LOAN_ID)
CONSTRAINT DISBERSEMENT_STATEMENT_FK 
FOREIGN KEY (STATEMENT_ID)
REFERENCES MONTHLY_STATEMENT (STATEMENT_ID)
ON UPDATE CASCADE
CREATE INDEX LOAN_PROCESS 
   ON LOAN_PROCEED_DISBERSEMENT (DISBERSEMENT_DATE, CHECK_AMOUNT)
  [COMPUTE STATISTICS]
);


CREATE TABLE "lOAN_IDENTIFICATION" (
  "LOAN_STATUS" VARCHAR2(100) NOT NULL,
  "RISK_FACTOR" VARCHAR2(100) NOT NULL,
  "EMPLOYEEID" NUMBER(10) NOT NULL,
  "LOAN_ID" NUMBER(10) NOT NULL,
CONSTRAINT EMLOYEE_IDENTIFICATION_FK 
FOREIGN KEY (EMLOYEEID)
REFERENCES EMLOYEES (EMLOYEEID)
CONSTRAINT IDENTIFICATION_LOAN_FK 
FOREIGN KEY (LOAN_ID)
REFERENCES LOAN_APPLICATION_FORM (LOAN_ID)
ON UPDATE CASCADE
CREATE INDEX IDENTIFICATION 
   ON LOAN_IDENTIFICATION (LOAN_STATUS, RISK_FACTOR)
 [COMPUTE STATISTICS]
);

CREATE TABLE "TRANSACTIONS" (
  "TRANSACTIONID" NUMBER(10) NOT NULL PRIMARY KEY, 
  "DATE_DUE" TIMESTAMP NOT NULL,
  "AMOUNT_BILLED" DECIMAL(12,4) NOT NULL,
  "DATE_RECEIVED" TIMESTAMP NOT NULL,
  "AMOUNT_RECEIVED" DECIMAL(12,4) NOT NULL,
  "INTEREST_PAID" DECIMAL(12,4) NOT NULL,
  "PRINCIPLE_APPLIED" DECIMAL(12,4) NOT NULL,
  "STATEMENT_ID" NUMBER(10) NOT NULL,
CONSTRAINT TRANSACTIONS_STATEMENT_FK 
FOREIGN KEY (STATEMENT_ID)
REFERENCES MONTHLY_STATEMENT (STATEMENT_ID)
ON UPDATE CASCADE
CREATE INDEX TRANSACTION_STATEMENT 
   ON TRANSACTIONS (DATE_DUE, AMOUNT_BILLED, DATE_RECEIVED, AMOUNT_RECEIVED, INTEREST_PAID, PRINCIPLE_APPLIED)
  [COMPUTE STATISTICS]
);


