CREATE TABLE CUSTOMER_INFO (
   CUSTOMER_SSN NUMBER(100) NOT NULL,
   FIRST_NAME VARCHAR(100) NOT NULL,
   LAST_NAME VARCHAR(100) NOT NULL UNIQUE,
   BIRTH_DATE NUMBER(2) NOT NULL,
   BIRHT_MONTH NUMBER(2) NOT NULL,
   BIRTH_YEAR NUMBER(4) NOT NULL,
   PHONE_TYPE VARCHAR2(100) NULL,
   PHONE_NUMBER NUMBER(10) NOT NULL UNIQUE,
   CITY VARCHAR(100) NOT NULL,
   STATE VARCHAR(100) NOT NULL,
   STREET VARCHAR(100) NOT NULL,
   BANK_INFO VARCHAR(100) NOT NULL,
   PRIMARY_INCOME DECIMAL(12,4) NULL,
   SECONDARY_INCOME DECIMAL(12,4) NULL,
   CONSTRAINT "PK_CUSTOMER_IDENTIFICATION" PRIMARY KEY (CUSTOMER_SSN)
   ON UPDATE CASCADE
 );
   CREATE INDEX "CUSTOMERINFO" ON CUSTOMER_INFO (PHONE_NUMBER, CITY, STATE, STREET, BANK_INFO);   
   
CREATE TABLE MONTHLY_STATEMENT(
  STATEMENT_ID NUMBER(10) NOT NULL,
  PRINCIPLE_BALANCE DECIMAL(12,4) NOT NULL,
  STATEMENT_DATE TIMESTAMP NOT NULL,
  PAYMENT_DUE_DATE TIMESTAMP NOT NULL,
  REMAINIG_PAYMENTS DECIMAL(12,4) NOT NULL,
  DATE_LAST_PAYMENT TIMESTAMP NOT NULL,
  CONSTRAINT "PK_MONTHLY_STATEMENT" PRIMARY KEY (STATEMENT_ID)
  ON UPDATE CASCADE
 );
   CREATE INDEX "STATEMENT_MONTH"
   ON MONTHLY_STATEMENT (PRINCIPLE_BALANCE, PAYMENT_DUE_DATE, REMAINIG_PAYMENTS, DATE_LAST_PAYMENT);
   
  CREATE TABLE EMPLOYEES (
   NUMBER(10) NOT NULL,
  OFFICERID NUMBER(10) NOT NULL UNIQUE,
  IDENTIFIERID NUMBER(10) NOT NULL UNIQUE,
  EMPL_FIRST_NAME VARCHAR(100) NOT NULL,
  EMPL_LAST_NAME VARCHAR(100) NOT NULL,
  CONSTRAINT "PK_EMPLOYEES_ID" PRIMARY KEY (EMPLOYEEID)
  CONSTRAINT "FK_EMOLOYEES_OFFICER" FOREIGN KEY (OFFICERID)
  REFERENCES EMPLOYEES (EMPLOYEEID)
  CONSTRAINT "FK_EMLOYEE_INDENTIFIER" FOREIGN KEY (IDENTIFIERID)
  REFERENCES EMLOYEES (EMLOYEEID)
  ON UPDATE CASCADE
  );
 CREATE UNIQUE INDEX "EMLOYEESINFO" 
 ON EMPLOYEES (EMPL_FIRST_NAME, EMPL_LAST_NAME);
  
CREATE TABLE LOAN_APPLICATION_FORM (
  LOAN_ID NUMBER(10) NOT NULL,
  INTEREST_RATE NUMBER(10) NOT NULL,
  LOAN_TYPE VARCHAR(100) NOT NULL,
  MONTHLY_PAYMENT DECIMAL(12,4) NOT NULL,
  RESTRICTION_ON_LOAN VARCHAR(100) NOT NULL,
  APLLICATION_DATE TIMESTAMP NOT NULL,
  LOAN_AMOUNT DECIMAL(12,4) NOT NULL,
  LOAN_TERM VARCHAR(100) NOT NULL,
  CUSTOMER_SSN NUMBER(10) NOT NULL,
  EMPLOYEEID NUMBER(10) NOT NULL,
  STATEMENT_ID NUMBER(10) NOT NULL,
  CONSTRAINT "PK_CUSTOMER_LOAN" PRIMARY KEY (LOAN_ID)
  CONSTRAINT "FK_CUSTOMER_FORM" FOREIGN KEY (CUSTOMER_SSN)
  REFERENCES CUSTOMER_INFO (CUSTOMER_SSN)
  CONSTRAINT "FK_EMPLOYEE_FORM" FOREIGN KEY (EMPLOYEEID)
  REFERENCES EMLOYEES (EMPLOYEEID)
  CONSTRAINT "FK_FORM_STATEMENT" FOREIGN KEY (STATEMENT_ID)
  REFERENCES MONTHLY_STATEMENT (STATEMENT_ID)
  ON UPDATE CASCADE
  );
CREATE INDEX "APPLICATIONFORM" 
   ON LOAN_APPLICATION_FORM (INTEREST_RATE, LOAN_TYPE, MONTHLY_PAYMENT, RESTRICTION_ON_LOAN, APLLICATION_DATE, LOAN_AMOUNT, LOAN_TERM);
 
CREATE TABLE TRANSACTIONS (
  TRANSACTIONID NUMBER(10) NOT NULL, 
  DATE_DUE TIMESTAMP NOT NULL,
  AMOUNT_BILLED DECIMAL(12,4) NOT NULL,
  DATE_RECEIVED TIMESTAMP NOT NULL,
  AMOUNT_RECEIVED DECIMAL(12,4) NOT NULL,
  INTEREST_PAID DECIMAL(12,4) NOT NULL,
  PRINCIPLE_APPLIED DECIMAL(12,4) NOT NULL,
  STATEMENT_ID NUMBER(10) NOT NULL,
  CONSTRAINT "PK_TRANSACTION" PRIMARY KEY (TRANSACTIONID)
  CONSTRAINT "FK_TRANSACTIONS_STATEMENT" FOREIGN KEY (STATEMENT_ID)
  REFERENCES MONTHLY_STATEMENT (STATEMENT_ID)
  ON UPDATE CASCADE
  );
 CREATE INDEX "TRANSACTION_STATEMENT" 
   ON TRANSACTIONS (DATE_DUE, AMOUNT_BILLED, DATE_RECEIVED, AMOUNT_RECEIVED, INTEREST_PAID, PRINCIPLE_APPLIED);
   
 CREATE TABLE LOAN_PROCEED_DISBERSEMENT (
  CHECK_ID NUMBER(10) NOT NULL,
  DISBERSEMENT_DATE TIMESTAMP NOT NULL,
  CHECK_AMOUNT DECIMAL(12,4) NOT NULL,
  LOAN_ID NUMBER(10) NOT NULL,
  STATEMENT_ID NUMBER(10) NOT NULL,
  CONSTRAINT "PK_CHECKID" PRIMARY KEY (CHECK_ID)
  CONSTRAINT "FK_DISBERSEMENT_LOAN" FOREIGN KEY (LOAN_ID)
  REFERENCES LOAN_APPLICATION_FORM (LOAN_ID)
  CONSTRAINT "FK_DISBERSEMENT_STATEMENT" FOREIGN KEY (STATEMENT_ID)
  REFERENCES MONTHLY_STATEMENT (STATEMENT_ID)
  ON UPDATE CASCADE
  );
  CREATE INDEX "LOAN_PROCESS" 
   ON LOAN_PROCEED_DISBERSEMENT (DISBERSEMENT_DATE, CHECK_AMOUNT);
  
  CREATE TABLE LOAN_IDENTIFICATION (
  LOAN_STATUS VARCHAR(100) NOT NULL,
  RISK_FACTOR VARCHAR(100) NOT NULL,
  EMPLOYEEID NUMBER(10) NOT NULL,
  LOAN_ID NUMBER(10) NOT NULL,
CONSTRAINT "FK_EMLOYEE_IDENTIFICATION" FOREIGN KEY (EMPLOYEEID)
REFERENCES EMLOYEES (EMPLOYEEID)
CONSTRAINT "FK_IDENTIFICATION_LOAN" FOREIGN KEY (LOAN_ID)
REFERENCES LOAN_APPLICATION_FORM (LOAN_ID)
ON UPDATE CASCADE
);
CREATE INDEX "IDENTIFICATION" 
   ON LOAN_IDENTIFICATION (LOAN_STATUS, RISK_FACTOR);

  
  